services:
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  appserver.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__Port=5672
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
    ports:
      - "8080:8080"

  appserver.worker:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__Port=5672
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
      - Email__Host=smtp.gmail.com
      - Email__Port=587
      - Email__Username=claudioappserve@gmail.com
      - Email__Password=vnzdmkomnzudrbwc
      - Email__From=claudioappserve@gmail.com
