apiVersion: v1
kind: Secret
metadata:
  name: appserver-secret
  namespace: appserver
type: Opaque
stringData:
  RabbitMq__UserName: guest
  RabbitMq__Password: guest
  Email__Username: claudioappserve@gmail.com
  Email__Password: vnzdmkomnzudrbwc
