FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["AppServer.Api/AppServer.Api.csproj", "AppServer.Api/"]
RUN dotnet restore "./AppServer.Api/AppServer.Api.csproj"
COPY . .
RUN dotnet build "./AppServer.Api/AppServer.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./AppServer.Api/AppServer.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AppServer.Api.dll"]

