name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: AppServer.Api/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/appserver-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/appserver-api:${{ github.sha }}

      - name: Build and push Worker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: AppServer.Worker/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/appserver-worker:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/appserver-worker:${{ github.sha }}