name: Build and Push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- nomes em lowercase (GHCR exige) ---
      - name: Set image names (lowercase)
        id: vars
        run: |
          OWNER_LC=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          REPO_LC=$(echo "${GITHUB_REPOSITORY#*/}" | tr '[:upper:]' '[:lower:]')
          echo "ghcr=ghcr.io/${OWNER_LC}/${REPO_LC}" >> $GITHUB_OUTPUT
          echo "dockerhub=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${REPO_LC}" >> $GITHUB_OUTPUT

      # --- Login GHCR ---
      - name: Login no GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- Login Docker Hub ---
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- Build e Push para os DOIS registries ---
      - name: Build e Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.vars.outputs.ghcr }}:latest
            ${{ steps.vars.outputs.dockerhub }}:latest